### ISSUE TITLE
Bug: Hovering triggers on both

### ISSUE THREAD

**Issue by SteffoSpieler** [FulytheFox/paw-up-userstyle#7]
When hovering with your mouse over the like or the dislike button, both buttons show the hover state.

![grafik](https://github.com/FulytheFox/paw-up-userstyle/assets/41108856/671411d3-6eb3-4f19-9c3e-fac79b5dbd3a)

**Comment by FulytheFox** [comment]
Hey, thank you for reporting this bug and sorry that the project was so inactive.

The issue should be now fixed with the new update to version 2.8. You can go to the [Paw Up!](https://userstyles.org/styles/169802) userstyle.org page and press the Update Style button to update the userstyle. If it still occurs after the update, please reopen this issue.
