### ISSUE TITLE
The paws don't show up anymore.

### ISSUE THREAD

**Issue by MarcusTheAnimator** [FulytheFox/paw-up-userstyle#8]
A lot of people are now having an issue of the paws just becoming blank and not showing up anymore.

**Comment by FulytheFox** [comment]
Hey, thank you for reporting! I'm sorry that the project was so inactive.

I think the bug had something to do with the installation process of the userstyle, because userstyles.org had a update.
I pushed an update to the userstyle so the issue should be now fixed. If it still occurs after a update or a reinstallation, please reopen this issue.
